language: python

sudo: false

services:
  - redis-server

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=pypy3

install:
  - pip install tox-travis

script:
  - tox -e $TOX_ENV
